services:
  postgres:
    image: postgres:15-alpine
    container_name: nestjs_postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_password
      POSTGRES_DB: nest_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nest_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
